name: Test Install

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        package: [onivim2, onivim2-nightly]
    steps:
      - uses: actions/checkout@v2
      - name: style
        run: brew style --cask Casks/${{ matrix.package }}.rb
